/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_greeting
  (JNIEnv *, jobject);

/*
 * Class:     JNI
 * Method:    getMessageFromInputString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_getMessageFromInputString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNI
 * Method:    getSumOfTwoNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_getSumOfTwoNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
